#ifndef INCLUDES_H
#define INCLUDES_H
#include <exception>
#include "highgui.h"
#include "cv.h"

#include <QMainWindow>
#include <iostream>
#include <QMainWindow>
#include <QGraphicsView>
#include <QGraphicsScene>
#include <QGraphicsItem>
#include <QFileDialog>
#include <QDebug>
#include <QDesktopWidget>
#include <QMessageBox>
#include <string>
#include "opencv2/core/core.hpp"
#include "opencv2/imgproc/imgproc.hpp"
#include "opencv2/highgui/highgui.hpp"
#include <stdio.h>
#include <stdlib.h>
#include "opencv2/gpu/gpu.hpp"
#include "opencv2/opencv.hpp"
#include <iostream>
#include <sys/timeb.h>
#include <fstream>
#include <dirent.h>
#include <assert.h>
#endif
